# Generated by Django 4.1.1 on 2022-09-19 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecitersProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='reciters/')),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('chapter_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=220)),
                ('surah_meaning', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('file_size', models.DecimalField(decimal_places=1, max_digits=19)),
                ('format', models.CharField(max_length=100)),
                ('audio_url', models.FileField(null=True, upload_to='surah/')),
                ('duration', models.IntegerField()),
                ('verse_timings', models.CharField(blank=True, max_length=300000000)),
                ('reciter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surah', to='reciters.recitersprofile')),
            ],
        ),
    ]
